const router = require('express').Router();
const controller = require('../controllers/manualModeController');
const { authenticateToken } = require('../middlewares/auth');
const { operatorAccess } = require('../middlewares/operatorAccess');
router.use(authenticateToken, operatorAccess);
router.post('/request', controller.requestManualMode);
router.post('/approve', controller.approveManualMode);
router.post('/extend', controller.extendManualMode);
router.post('/reject', controller.rejectManualMode);
router.get('/all', controller.getAllManualModeRequests);
router.get('/status', controller.currentUserMode);
router.post('/capture', controller.postManualModeLog);
router.post('/end', controller.endManualModeSession);
module.exports = router;
